name: 'ModernTribe - Git Deploy'
description: 'Deploy to a Git repository'
author: 'moderntribe'
inputs:
  git_url:
    required: true
    description: Git Url
  branch:
    required: true
    description: Branch being deployed
  ssh_private_key:
    required: false
    description: SSH Private Key
  folder:
    required: false
    default: .
    description: Git folder path
runs:
    using: composite
    steps:
      - name: Setup SSH
        if: ${{ inputs.ssh_private_key != '' }}
        uses: moderntribe/actions/utils/ssh-agent@v1
        with:
          ssh_private_key: ${{ secrets.ssh_private_key }}

      - name: Deploy to ${{ inputs.app }}
        shell: bash
        working-directory: ${{ inputs.folder }}
        run: |
          git remote add deploy_server ${{ inputs.git_url }}
          git push deploy_server ${{ inputs.branch }}:master --force