name: ModernTribe - Create Review App
description: Create Review App in Dokku Server
author: moderntribe
inputs:
    app_name:
      required: true
      description: Dokku Original App Name
    review_app_name:
      required: true
      description: Dokku Review App Name
    server:
      required: true
      description: Server Name
    server_url:
      required: true
      description: Server URL
    ssh_private_key:
      required: true
      description: SSH Private Key
    github_pat_token:
      required: true
      description: Github Personal Access token
    gha_url:
      required: true
      description: Github Actions Run URL
runs:
  using: composite
  steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ inputs.ssh_private_key }}

      - name: Check if ${{ inputs.app_name }} already exists
        id: test_app
        shell: bash
        run: |
          ssh-keyscan ${{ inputs.server_url }}
          exists=$(${SSH_COMMAND} dokku@${{ inputs.server_url }} apps:exists ${{ inputs.app_name }} && echo "true" || echo "false")
          echo "##[set-output name=app_exists;]$(echo ${exists})"

      - name: Repository Dispatch | Launch ${{ inputs.review_app_name }}
        if: steps.test_app.outputs.app_exists == 'false'
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: moderntribe/dokku-ansible
          event-type: create-review-app
          token: "${{ inputs.github_pat_token }}"
          client-payload: |
            {
              "review_app_name": "${{ inputs.review_app_name }}",
              "app_name": "${{ inputs.app_name }}",
              "server": "${{ inputs.server }}",
              "action_url": "${{ inputs.gha_url }}"
            }