name: 'SquareOne - Build Node'
description: 'Sets up Node and installs deps using yarn.'
author: 'moderntribe'
inputs:
  folder:
    required: false
    default: .
    description: Folder node files should be built
runs:
  using: composite
  steps:
    - name: Setup node version
      uses: actions/setup-node@v2
      with:
        node-version-file: ${{ inputs.folder }}/.nvmrc
        cache: npm
        cache-dependency-path: ${{ inputs.folder }}/package-lock.json

    - name: Install Yarn dependencies
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: |
        yarn install

    - name: NPM build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: |
        npm run validate --if-present
        npm run server_dist --if-present

    - name: Gulp Build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: |
        (test -f gulpfile.js && gulp build) || echo gulpfile.js does not exist, skipping step

    - name: Grunt Build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: |
        (test -f Gruntfile.js &&grunt dist) || echo Gruntfile.js does not exist, skipping step