
name: 'SquareOne - Build Node'
description: 'Sets up Node and installs deps using yarn.'
author: 'moderntribe'
runs:
    using: 'composite'
    steps:
        - name: Setup node version
          uses: actions/setup-node@v2
          with:
            node-version-file: '.nvmrc'

        - name: Yarn install and build
          shell: bash
          run: |
            yarn install
            npm run validate
            npm run server_dist