name: 'SquareOne - Build Node'
description: 'Sets up Node and installs deps using yarn.'
author: 'moderntribe'
inputs:
  folder:
    required: false
    default: .
    description: Folder node files should be built
runs:
  using: composite
  steps:
    - name: Setup node version
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.folder }}/.nvmrc

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Get yarn hash key
      shell: bash
      id: yarn-hashfile
      working-directory: ${{ inputs.folder }}
      run: echo "hash=${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ steps.yarn-hashfile.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-yarn

    - name: Install Yarn dependencies
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: yarn

    - name: NPM validate
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: npm run validate --if-present

    - name: NPM build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: npm run server_dist --if-present

    - name: Gulp Build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: (test -f gulpfile.js && gulp build) || echo gulpfile.js does not exist, skipping step

    - name: Grunt Build
      working-directory: ${{ inputs.folder }}
      shell: bash
      run: (test -f Gruntfile.js && grunt dist) || echo Gruntfile.js does not exist, skipping step
