name: 'SquareOne - Slack Message'
description: 'Sends message to Slack Webhook.'
author: 'moderntribe'
inputs:
    webhook_url:
      required: true
      description: 'Incoming Webhook URL'
    server_url:
      required: true
      description: Server URL
    message:
      required: true
      description: Slack message
    gha_url:
      required: true
      description: Github Actions Run URL
    color:
      required: true
      description: Slack Message Color

runs:
    using: 'composite'
    steps:
      - name: Slack Message
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: "${{ inputs.message }}"
          attachments: |
            [
              {
                "color": "${{ inputs.color }}",
                "fields": [
                  {
                    "title": "Server URL",
                    "value": "${{ inputs.server_url }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }
            ]