name: 'ModernTribe - Slack Message'
description: 'Sends message to Slack Webhook.'
author: 'moderntribe'
inputs:
    branch:
      required: true
      description: Branch being deployed
    environment:
      required: true
      description: Environment
    slack_webhook_url:
      required: true
      description: Incoming Webhook URL
    status:
      required: true
      description: Job Status
    app_url:
      required: true
      description: App URL
    gha_url:
      required: true
      description: Github Actions Run URL

runs:
    using: composite
    steps:
      - shell: bash
        run: echo "Status=${{ inputs.status }}"

      - name: Slack Success Notification
        uses: slackapi/slack-github-action@v1
        if: ${{ inputs.status == 'success' }}
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "icon_emoji": ":rocket:",
              "username": "GHA Deploy Bot",
              "text": ":white_check_mark: Successful Deployment branch `${{ inputs.branch }}` to *${{ inputs.environment }}*",
              "attachments": [{
                "color": "good",
                "title_link": "${{ inputs.app_url }}",
                "fields": [{
                    "title": "Server URL",
                    "value": "${{ inputs.app_url }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }]
            }


      - name: Slack Failure Notification
        uses: slackapi/slack-github-action@v1
        if: ${{ inputs.status == 'failure' }}
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "icon_emoji": ":rocket:",
              "username": "GHA Deploy Bot",
              "text": ":x: Failed Deployment to ${{ inputs.environment }}",
              "attachments": [{
                "color": "bad",
                "title_link": "${{ inputs.app_url }}",
                "fields": [{
                    "title": "Server URL",
                    "value": "${{ inputs.app_url }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }]
            }

      - name: Slack Cancel Notification
        uses: slackapi/slack-github-action@v1
        if: ${{ inputs.status == 'cancelled' }}
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "icon_emoji": ":rocket:",
              "username": "GHA Deploy Bot",
              "text": ":x: Canceled Deployment to ${{ inputs.environment }}",
              "attachments": [{
                "color": "bad",
                "title_link": "${{ inputs.app_url }}",
                "fields": [{
                    "title": "Server URL",
                    "value": "${{ inputs.app_url }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }]
            }