name: 'SquareOne - Slack Message'
description: 'Sends message to Slack Webhook.'
author: 'moderntribe'
inputs:
    webhook_url:
      required: true
      description: 'Incoming Webhook URL'
      default: ${{ secrets.SLACK_WEBHOOK }}
    title:
      required: true
      description: Slack Message Title
    message:
      required: true
      description: Slack message
    gha_url:
      required: true
      description: Github Actions Run URL
    failure:
      required: true
      description: Message is failure or success

runs:
    using: 'composite'
    steps:
      - name: SUCCESS
        if: ${{ inputs.failure }} == "false"
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: ":green_check: Successful on Review App Deployment"
          attachments: |
            [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "${{ inputs.title }}",
                    "value": "${{ inputs.message }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }
            ]

      - name: FAILURE
        if: ${{ inputs.failure }} == "true"
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: ":x: Failed on Review App Deployment"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "${{ inputs.title }}",
                    "value": "${{ inputs.message }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ inputs.gha_url }}"
                  }
                ]
              }
            ]