name: Reusable Workflow - Create Review App
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: Dokku Original App Name
    secrets:
      github_pat_token:
        required: true
      server:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set common variables
        uses: moderntribe/actions/utils/common-variables@v1
        with:
          app_name: ${{ inputs.app_name }}

      - name: Create review app ${{ inputs.review_app_name }}
        uses: moderntribe/actions/dokku/create-review-app@v1
        with:
          app_name: ${{ inputs.app_name }}
          review_app_name: ${{ inputs.review_app_name }}
          server: ${{ secrets.server }}
          github_pat_token: ${{ secrets.github_pat_token }}
          gha_url: ${{ inputs.gha_url }}
