name: ModernTribe - Commit Files
description: Commit files in the same repository
author: moderntribe
inputs:
  folder:
    required: true
    description: Folder to add files to the commit
runs:
  using: composite
  steps:
    - name: Config Git
      shell: bash
      run: |
        git config --global user.name "github actions modern tribe"
        git config --global user.email "devops@tri.be"

    - name: Commit files
      shell: bash
      run: |
        git add ${{ inputs.folder }} --force
        git commit --allow-empty -m "Commiting Deploy files"