name: Reusable Workflow - Delete Review App
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: Dokku Original App Name
      pr_number:
        required: false
        type: string
        description: Pull Request Number
    secrets:
      github_pat_token:
        required: true
      server:
        required: true

jobs:
  delete_review_app:
    runs-on: ubuntu-latest
    steps:
      - name: Set common variables
        uses: moderntribe/actions/utils/common-variables@v1
        with:
          app_name: ${{ inputs.app_name }}
          pr_number: ${{ inputs.pr_number }}

      - name: Delete review app ${{ env.REVIEW_APP }}
        uses: moderntribe/actions/dokku/delete-review-app@v1
        with:
          app_name: ${{ inputs.app_name }}
          review_app_name: ${{ env.REVIEW_APP }}
          server: ${{ secrets.server }}
          github_pat_token: ${{ secrets.github_pat_token }}
          gha_url: ${{ env.GHA_URL }}